keyword:
  - "how are you"
  - "purpose"
  - "topics"
  - "phishing"
  - "password"
  - "safe browsing"

response:
  - "I'm good"
  - "I am a Cybersecurity Awareness Bot and my purpose is to educate you about online safety"
  - "You can ask me about phishing, passwords and safe browsing"
  - "Beware of any unknown emails or messages. Always verify the sender."
  - "Ensure you use a strong and unique password!!!"
  - "Use updated browsers, avoid unsafe websites and enable HTTPS."
