name: ChatBot CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Check responses.yml exists
        shell: pwsh
        run: |
          if (Test-Path "responses.yml") {
            Write-Host "responses.yml found!"
          } else {
            Write-Error "responses.yml is MISSING!"
            exit 1
          }

      - name: Check project files exist
        shell: pwsh
        run: |
          Write-Host "Project files found!"
          Get-ChildItem -Recurse *.cs | Select-Object Name
